book_list = [
    {"title": "The Lord of the Rings", "authors": ["J.R.R. Tolkien"]},
    {"title": "Pride and Prejudice", "authors": ["Jane Austen"]},
    {"title": "To Kill a Mockingbird", "authors": ["Harper Lee"]},
    {"title": "1984", "authors": ["George Orwell"]},
    {"title": "One Hundred Years of Solitude", "authors": ["Gabriel García Márquez"]},
    {"title": "The Great Gatsby", "authors": ["F. Scott Fitzgerald"]},
    {"title": "Moby Dick", "authors": ["Herman Melville"]},
    {"title": "Hamlet", "authors": ["William Shakespeare"]},
    {"title": "The Hitchhiker's Guide to the Galaxy", "authors": ["Douglas Adams"]},
    {"title": "Little Women", "authors": ["Louisa May Alcott"]},
    {"title": "The Picture of Dorian Gray", "authors": ["Oscar Wilde"]},
    {"title": "Jane Eyre", "authors": ["Charlotte Brontë"]},
    {"title": "The Catcher in the Rye", "authors": ["J.D. Salinger"]},
    {"title": "Brave New World", "authors": ["Aldous Huxley"]},
    {"title": "The Odyssey", "authors": ["Homer"]},
    {"title": "Frankenstein", "authors": ["Mary Shelley"]},
    {"title": "Dracula", "authors": ["Bram Stoker"]},
    {"title": "Wuthering Heights", "authors": ["Emily Brontë"]},
    {"title": "The Old Man and the Sea", "authors": ["Ernest Hemingway"]},
    {"title": "Alice's Adventures in Wonderland", "authors": ["Lewis Carroll"]},
]